import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')
drive.mount("/content/drive/", force_remount=True)
!ls
PrintMARC = pd.read_table('/content/drive/<Insert Filepath>/PrintPharmacy202405.txt', header=0, delimiter='\t', low_memory=False, encoding = 'ISO-8859-1')
list(PrintMARC.columns.values)
ElectronicMARC = pd.read_table('/content/drive/<Insert Filepath>/ElectronicPharmacy202405.txt', header=0, delimiter='\t', low_memory=False, encoding = 'ISO-8859-1')
list(ElectronicMARC.columns.values)
KBART = pd.read_table('/content/drive/<Insert Filepath>/Kbart.txt', header=0, delimiter='\t', low_memory=False)
list(KBART.columns.values)
ElectronicMARC['001'] = ElectronicMARC['001'].astype(str)
ElectronicMARC['001'] = ElectronicMARC['001'].str.replace('ocm','')
ElectronicMARC['001'] = ElectronicMARC['001'].str.replace('ocn','')
ElectronicMARC['001'] = ElectronicMARC['001'].str.replace('on','')
ElectronicMARC['001'] = ElectronicMARC['001'].str.replace('\\','')
ElectronicMARC['001'] = ElectronicMARC['001'].str.strip()
ElectronicMARC['001'] = ElectronicMARC['001'].str.lstrip('0')
KBART['oclc_number'] = KBART['oclc_number'].astype(str)
KBART['oclc_number']= KBART['oclc_number'].replace(r'\.0$', '', regex=True)
KBART['oclc_number'] = KBART['oclc_number'].str.strip()
PrintMARC.head(5)
ElectronicMARC.head(5)
KBART.head(5)
import sqlite3
conn = sqlite3.connect("Pharmacy202405.db")
cursor = conn.cursor()
cursor.execute("DROP TABLE IF EXISTS Pharmacy202405")
PrintMARC.to_sql("PrintMARC", conn, if_exists='replace', index=False)
LHRs = pd.read_sql("""SELECT * FROM PrintMARC WHERE [000$06] In ('u','v','x','y')""", conn)
LHRs.to_sql("LHRs", conn, if_exists='replace', index=False)
Bibs = pd.read_sql("""SELECT * FROM PrintMARC WHERE [000$06] Not In ('u','v','x','y')""", conn)
Bibs.to_sql("Bibs", conn, if_exists='replace', index=False)
JoinedPrint = pd.read_sql("""SELECT Bibs.[001], Bibs.[000$06], Bibs.[000$07], Bibs.[245$a], Bibs.[650$a], Bibs.[650$x], LHRs.[852$b], LHRs.[008$06] FROM Bibs INNER JOIN LHRs ON Bibs.[001]=LHRs.[004]""", conn)
JoinedPrint.to_sql("JoinedPrint", conn, if_exists='replace', index=False)
JoinedPrint.head(5)
Serials =  pd.read_sql("""SELECT * FROM JoinedPrint WHERE [000$07] In ('s','i') AND ([650$a] Like '%Pharma%' OR [650$a] Like '%Therap%' OR [650$x] Like '%Pharma%' OR [650$x] Like '%Therap%' OR [650$x] Like '%Treatment%') AND [852$b] Not In ('WVUT','WVUP','WVUB','WVUS') AND [008$06] == '4'""", conn)
Serials.head(5)
Serials = Serials.drop_duplicates(subset=['001'])
Serials['001'] = Serials['001'].astype(str)
Serials['001'] = Serials['001'].str.replace('ocm','')
Serials['001'] = Serials['001'].str.replace('ocn','')
Serials['001'] = Serials['001'].str.replace('on','')
Serials['001'] = Serials['001'].str.replace('\\','')
Serials['001'] = Serials['001'].str.strip()
Serials['001'] = Serials['001'].str.lstrip('0')
Serials.to_csv('/content/drive/<Insert Filepath>/Pharmacy202405--Serials.txt', sep='\t', mode='a')
HSLSerials = pd.read_sql("""SELECT * FROM JoinedPrint WHERE [000$07] In ('s','i') AND ([650$a] Like '%Pharma%' OR [650$a] Like '%Therap%' OR [650$x] Like '%Pharma%' OR [650$x] Like '%Therap%' OR [650$x] Like '%Treatment%') AND [852$b] In ('WVUH', 'WVUD') AND [008$06] == '4'""", conn)
HSLSerials = HSLSerials.drop_duplicates(subset=['001'])
HSLSerials['001'] = HSLSerials['001'].astype(str)
HSLSerials['001'] = HSLSerials['001'].str.replace('ocm','')
HSLSerials['001'] = HSLSerials['001'].str.replace('ocn','')
HSLSerials['001'] = HSLSerials['001'].str.replace('on','')
HSLSerials['001'] = HSLSerials['001'].str.replace('\\','')
HSLSerials['001'] = HSLSerials['001'].str.strip()
HSLSerials['001'] = HSLSerials['001'].str.lstrip('0')
HSLSerials.to_csv('/content/drive/<Insert Filepath>/Pharmacy202405--HSLSerials.txt', sep='\t', mode='a')
ElectronicMARC.to_sql("eMARC", conn, if_exists='replace', index=False)
KBART.to_sql("KBART", conn, if_exists='replace', index=False)
CurrentKBART = pd.read_sql("""SELECT [publication_title],[oclc_number],[coverage_depth],[date_last_issue_online],[embargo_info], [oclc_collection_name], [online_identifier], [print_identifier] FROM KBART WHERE ([date_last_issue_online] Is Null OR [embargo_info] Is Not Null) AND [coverage_depth] == 'fulltext'""", conn)
CurrentKBART.to_sql("CurrentKBART", conn, if_exists='replace', index=False)
JoinedElectronic = pd.read_sql("""SELECT * FROM CurrentKBART LEFT JOIN eMARC ON CurrentKBART.[oclc_number]=eMARC.[001]""", conn)
JoinedElectronic.to_sql("JoinedElectronic", conn, if_exists='replace', index=False)
ESerials = pd.read_sql("""SELECT * FROM JoinedElectronic WHERE [000$07] In ('s','i') AND ([650$a] Like '%Pharma%' OR [650$a] Like '%Therap%' OR [650$x] Like '%Pharma%' OR [650$x] Like '%Therap%' OR [650$x] Like '%Treatment%')""", conn)
ESerials = ESerials.drop_duplicates(subset=['001'])
ESerials.to_csv('/content/drive/<Insert Fielpath>/Pharmacy202405--ESerials.txt', sep='\t', mode='a')